services:
  db:
    image: mariadb:10.5
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WP_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_ADMIN_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
    networks:
      - wp-network

  wordpress:
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WP_DB_USERNAME}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WP_DATABASE_NAME}
      WP_SITE_TITLE: ${WP_SITE_TITLE}
      WP_SITE_ADMIN_USERNAME: ${WP_SITE_ADMIN_USERNAME}
      WP_SITE_ADMIN_PASSWORD: ${WP_SITE_ADMIN_PASSWORD}
      WP_SITE_ADMIN_EMAIL: ${WP_SITE_ADMIN_EMAIL}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - wp-network

volumes:
  db_data:
  wordpress_data:

networks:
  wp-network:
    driver: bridge
